### ISSUE TITLE
InSecure Transport error

### ISSUE THREAD

**Issue by stepan-neretin7** [thec0sm0s/Flask-Discord#6] opened 2020-04-28 05:36 UTC
Hi, i start my discord app on flask ngrok server and try ro run it
but I got such an error ... What should I do, tell me please?
![изображение](https://user-images.githubusercontent.com/28489754/80450884-2ffe1080-892b-11ea-83fd-0c80ee5a875f.png)

**Comment by KittyLe** [comment] 2020-04-28 06:07
Try adding `os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'` before you do `app.run()`.

**Comment by thec0sm0s** [comment] 2020-04-28 06:45
Duplicate of #3

**Closed** 2020-04-28 13:51 UTC
